version: "3.8"

services:

  temperature-conversion-api:
    container_name: temperature-conversion-api
    image: temperature-conversion-api
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"